site_name: HashPress Docs
site_url: https://www.hashpress.io/
theme:
    name: material
    logo: assets/logo.svg
    favicon: assets/logo.svg
    # custom_dir: overrides
    features:
        # - navigation.tabs
        - navigation.sections
        # - toc.integrate
        # - navigation.top
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: orange
          accent: orange
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: orange
          accent: orange

plugins: []

extra:
    social:
        - icon: fontawesome/brands/x-twitter
          link: https://twitter.com/HederaHashPress
        - icon: fontawesome/brands/discord
          link: https://discord.gg/qHEyv3mapz
        - icon: fontawesome/brands/github
          link: https://github.com/louweal

extra_css:
    - main.css

markdown_extensions:
    - admonition
    - footnotes
    - attr_list

copyright: |
    &copy; 2024 <a href="https://www.hashpress.io"  target="_blank" rel="noopener">HashPress</a>
